name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature or improvement.
      placeholder: "It would be great if..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Why?
      description: What problem does this solve, or what use case does it enable?
      placeholder: "Currently I have to... / This would help with..."
    validations:
      required: false

  - type: textarea
    id: ideas
    attributes:
      label: Ideas / Mockups
      description: Optional implementation ideas, mockups, or examples from other apps.
    validations:
      required: false

  - type: dropdown
    id: service
    attributes:
      label: Which part is affected?
      options:
        - Frontend (UI)
        - Backend (API)
        - Game Player
        - Game Service
        - Documentation
        - Don't know
    validations:
      required: false
