import {
  // Audio & Music (15 icons)
  Music,
  Mic,
  Radio,
  Headphones,
  Volume2,
  Volume,
  VolumeX,
  Speaker,
  Podcast,
  Disc,
  Disc2,
  Disc3,
  AudioLines,
  AudioWaveform,
  Music2,
  // Video & Film (18 icons)
  Film,
  Video,
  VideoOff,
  Camera,
  CameraOff,
  Clapperboard,
  Tv,
  Tv2,
  Monitor,
  MonitorPlay,
  Projector,
  Webcam,
  Play,
  PlayCircle,
  Pause,
  PauseCircle,
  SkipForward,
  SkipBack,
  // Images & Photography (12 icons)
  Image,
  ImageOff,
  ImagePlus,
  Images,
  GalleryHorizontal,
  GalleryVertical,
  GalleryVerticalEnd,
  Crop,
  Filter,
  Aperture,
  Focus,
  ScanFace,
  // Sports & Fitness (15 icons)
  Trophy,
  Medal,
  Target,
  Swords,
  Dumbbell,
  Bike,
  Activity,
  Footprints,
  Mountain,
  Waves,
  Sailboat,
  PersonStanding,
  TrendingUp,
  Zap,
  Flame,
  // Food & Dining (18 icons)
  Coffee,
  CupSoda,
  Pizza,
  Cake,
  IceCream,
  Apple,
  Banana,
  Cherry,
  Egg,
  Fish,
  Salad,
  Utensils,
  UtensilsCrossed,
  Wine,
  Beer,
  Martini,
  Milk,
  CakeSlice,
  // Travel & Places (18 icons)
  Plane,
  Car,
  Bus,
  Train,
  Ship,
  Rocket,
  Luggage,
  Map,
  MapPin,
  MapPinned,
  Compass,
  Palmtree,
  Tent,
  Hotel,
  Home,
  Building,
  Store,
  Signpost,
  // Reading & Arts (15 icons)
  Book,
  BookOpen,
  BookMarked,
  BookCopy,
  Library,
  GraduationCap,
  Palette,
  Paintbrush,
  Brush,
  Pen,
  PenTool,
  Pencil,
  Feather,
  Layers,
  Sparkles,
  // Gaming Icons (18 icons)
  Gamepad,
  Gamepad2,
  Joystick,
  Puzzle,
  Dices,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Spade,
  Club,
  Diamond,
  Shield,
  ShieldCheck,
  Axe,
  Wand2,
  Bomb,
  Skull,
  Ghost,
  // Hearts & Love (9 icons)
  Heart,
  HeartPulse,
  HeartCrack,
  HeartHandshake,
  HeartOff,
  ThumbsUp,
  ThumbsDown,
  HandHeart,
  Laugh,
  // Stars & Ratings (8 icons)
  Star,
  StarHalf,
  StarOff,
  Sparkle,
  Crown,
  Gem,
  Award,
  // Bookmarks & Collections (8 icons)
  Bookmark,
  BookmarkPlus,
  BookmarkMinus,
  BookmarkCheck,
  Pin,
  PinOff,
  Paperclip,
  Link,
  // Emotions & Reactions (10 icons)
  Smile,
  SmilePlus,
  Meh,
  Frown,
  Angry,
  Users,
  User,
  UserCheck,
  UserPlus,
  // Folders & Files (25 icons)
  Folder,
  FolderOpen,
  FolderClosed,
  FolderPlus,
  FolderMinus,
  FolderArchive,
  FolderCheck,
  FolderCog,
  FolderHeart,
  FolderSync,
  File,
  FileText,
  FileCheck,
  FilePlus,
  FileMinus,
  FileArchive,
  FileAudio,
  FileVideo,
  FileImage,
  Files,
  Inbox,
  Archive,
  Package,
  Package2,
  PackageCheck,
  // Organization & Productivity (20 icons)
  Boxes,
  Box,
  Container,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  List,
  ListChecks,
  ListOrdered,
  Kanban,
  Layers3,
  Grid3x3,
  LayoutGrid,
  LayoutList,
  Table,
  Columns,
  Rows,
  AlignLeft,
  AlignCenter,
  // Flags & Markers (7 icons)
  Flag,
  FlagTriangleRight,
  FlagTriangleLeft,
  Milestone,
  Tags,
  Tag,
  Hash,
  // Badges & Achievements (10 icons)
  Badge,
  BadgeCheck,
  BadgeAlert,
  BadgeHelp,
  ShieldAlert,
  Crosshair,
  Gift,
  PartyPopper,
  // Energy & Power (6 icons)
  Sun,
  Moon,
  Lightbulb,
  Battery,
  BatteryCharging,
  Bolt,
  // Security & Keys (7 icons)
  Key,
  KeyRound,
  Lock,
  LockOpen,
  Unlock,
  Fingerprint,
  ListVideo, // Fallback icon

  // ============================================
  // NEW ICONS - Adding 367 icons to reach 600
  // ============================================

  // Nature & Weather (45 icons)
  Cloud,
  CloudRain,
  CloudSnow,
  CloudSun,
  CloudMoon,
  CloudFog,
  CloudDrizzle,
  CloudLightning,
  Snowflake,
  Rainbow,
  Sunrise,
  Sunset,
  Thermometer,
  ThermometerSun,
  ThermometerSnowflake,
  Wind,
  Tornado,
  Droplets,
  Droplet,
  Umbrella,
  TreePine,
  TreeDeciduous,
  Trees,
  Sprout,
  Leaf,
  Flower,
  Flower2,
  Clover,
  Shrub,
  Vegan,
  TreePalm,
  MountainSnow,
  Shell,
  Cloudy,
  CloudOff,
  CloudCog,
  CloudDownload,
  CloudUpload,
  SunMoon,
  SunDim,
  SunMedium,
  MoonStar,
  Haze,
  Eclipse,
  Stars,

  // Animals (18 icons)
  Cat,
  Dog,
  Rabbit,
  Rat,
  Squirrel,
  Bird,
  Bug,
  Turtle,
  Snail,
  Worm,
  BugPlay,
  BugOff,
  Bone,
  Beef,
  PawPrint,
  FishSymbol,
  Feather as FeatherAnimal,
  FishOff,

  // Technology (50 icons)
  Cpu,
  HardDrive,
  Database,
  DatabaseBackup,
  Server,
  ServerCog,
  ServerCrash,
  Terminal,
  TerminalSquare,
  Code,
  Code2,
  FileCode,
  FileCode2,
  Braces,
  Binary,
  Wifi,
  WifiOff,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  BluetoothSearching,
  Smartphone,
  Tablet,
  Laptop,
  Laptop2,
  Mouse,
  MousePointer,
  MousePointer2,
  Keyboard,
  Usb,
  HardDriveDownload,
  HardDriveUpload,
  Plug,
  Power,
  PowerOff,
  QrCode,
  ScanLine,
  Scan,
  Router,
  Cable,
  Cast,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Nfc,
  MonitorSmartphone,
  ServerOff,
  DatabaseZap,

  // Shapes & Symbols (40 icons)
  Circle,
  CircleDot,
  Square,
  SquareCheck,
  SquareDot,
  Triangle,
  Pentagon,
  Hexagon,
  Octagon,
  Plus,
  PlusCircle,
  PlusSquare,
  Minus,
  MinusCircle,
  MinusSquare,
  XCircle,
  XSquare,
  Equal,
  EqualNot,
  Divide,
  Percent,
  Infinity,
  CircleSlash,
  SquareSlash,
  AtSign,
  DollarSign,
  Euro,
  PoundSterling,
  IndianRupee,
  JapaneseYen,
  SwissFranc,
  RussianRuble,
  Asterisk,
  CircleDashed,
  SquareDashedBottom,
  TriangleAlert,
  OctagonAlert,
  CircleAlert,
  CircleCheck,
  SquareX,

  // Communication (35 icons)
  Mail,
  MailOpen,
  MailCheck,
  MailX,
  MailPlus,
  MailMinus,
  MailWarning,
  MailQuestion,
  MessageCircle,
  MessageSquare,
  MessageCircleQuestion,
  MessagesSquare,
  Send,
  SendHorizontal,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Voicemail,
  Contact,
  Contact2,
  Megaphone,
  Bell,
  BellOff,
  BellRing,
  BellDot,
  BellMinus,
  BellPlus,
  Rss,
  AtSign as AtSignComm,
  Reply,
  Forward,

  // Time & Calendar (30 icons)
  Clock,
  Clock1,
  Clock2,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  Clock10,
  Clock11,
  Clock12,
  Timer,
  TimerOff,
  TimerReset,
  Hourglass,
  AlarmClock,
  AlarmClockOff,
  Calendar,
  CalendarDays,
  CalendarCheck,
  CalendarClock,
  CalendarX,
  CalendarPlus,
  CalendarMinus,
  CalendarRange,
  CalendarHeart,
  History,
  Watch,

  // Business & Finance (35 icons)
  Briefcase,
  CreditCard,
  Receipt,
  Banknote,
  Coins,
  Wallet,
  PiggyBank,
  TrendingDown,
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  LineChart,
  PieChart,
  Scale,
  Calculator,
  Landmark,
  Building2,
  ShoppingBag,
  ShoppingCart,
  ShoppingBasket,
  Truck,
  CircleDollarSign,
  BadgeDollarSign,
  BadgePercent,
  ReceiptText,
  HandCoins,
  ArrowUpDown,
  ArrowDownUp,
  Presentation,
  BriefcaseBusiness,
  Factory,
  Warehouse,
  ReceiptEuro,
  ReceiptPoundSterling,

  // Health & Medical (20 icons)
  Pill,
  Stethoscope,
  Syringe,
  Ambulance,
  Cross,
  Hospital,
  Dna,
  Microscope,
  TestTube,
  TestTubes,
  FlaskConical,
  FlaskRound,
  Accessibility,
  Brain,
  Ear,
  Eye,
  EyeOff,
  Hand,
  Scan as MedicalScan,
  HeartHandshake as MedicalHeart,

  // Tools & Construction (34 icons)
  Wrench,
  Hammer,
  Drill,
  Pickaxe,
  Shovel,
  Scissors,
  Ruler,
  CircuitBoard,
  Component,
  Settings,
  Settings2,
  Cog,
  Sliders,
  SlidersHorizontal,
  SlidersVertical,
  Construction,
  Gauge,
  Magnet,
  Unlink,
  Search,
  SearchCheck,
  SearchX,
  SearchCode,
  SearchSlash,
  Telescope,
  Scaling,
  Pipette,
  Paintbrush2,
  PaintBucket,
  Eraser,
  Highlighter,
  Shapes,
  Slice,
  ZoomIn,

  // Arrows & Navigation (35 icons)
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowUpLeft,
  ArrowDownRight,
  ArrowDownLeft,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  ChevronsLeftRight,
  MoveUp,
  MoveDown,
  MoveLeft,
  MoveRight,
  MoveHorizontal,
  MoveVertical,
  Move,
  MoveDiagonal,
  MoveDiagonal2,
  Maximize,
  Minimize,
  Maximize2,
  Minimize2,
  Expand,
  Shrink,
  Navigation,
  Navigation2,

  // Miscellaneous (22 icons)
  Glasses,
  Lamp,
  LampDesk,
  LampFloor,
  LampCeiling,
  LampWallDown,
  LampWallUp,
  Flashlight,
  FlashlightOff,
  Cigarette,
  Baby,
  Shirt,
  Sofa,
  Bed,
  BedDouble,
  BedSingle,
  Bath,
  Armchair,
  DoorOpen,
  DoorClosed,
  Blinds,
  Fan,
  type LucideIcon,
} from 'lucide-react';

/**
 * Curated set of 600 icons for user playlists
 * Organized by category for easy browsing
 * Expanded from original 233 icons to provide maximum choice
 */
export const PLAYLIST_ICONS = {
  // ============================================
  // ORIGINAL ICONS (233 icons)
  // ============================================

  // Media & Entertainment - Audio (15 icons)
  music: Music,
  music2: Music2,
  mic: Mic,
  radio: Radio,
  headphones: Headphones,
  volume2: Volume2,
  volume: Volume,
  volumeX: VolumeX,
  speaker: Speaker,
  podcast: Podcast,
  disc: Disc,
  disc2: Disc2,
  disc3: Disc3,
  audioLines: AudioLines,
  audioWaveform: AudioWaveform,

  // Media & Entertainment - Video (18 icons)
  film: Film,
  video: Video,
  videoOff: VideoOff,
  camera: Camera,
  cameraOff: CameraOff,
  clapperboard: Clapperboard,
  tv: Tv,
  tv2: Tv2,
  monitor: Monitor,
  monitorPlay: MonitorPlay,
  projector: Projector,
  webcam: Webcam,
  play: Play,
  playCircle: PlayCircle,
  pause: Pause,
  pauseCircle: PauseCircle,
  skipForward: SkipForward,
  skipBack: SkipBack,

  // Media & Entertainment - Images (12 icons)
  image: Image,
  imageOff: ImageOff,
  imagePlus: ImagePlus,
  images: Images,
  galleryHorizontal: GalleryHorizontal,
  galleryVertical: GalleryVertical,
  galleryVerticalEnd: GalleryVerticalEnd,
  crop: Crop,
  filter: Filter,
  aperture: Aperture,
  focus: Focus,
  scanFace: ScanFace,

  // Activities - Sports (15 icons)
  trophy: Trophy,
  medal: Medal,
  target: Target,
  swords: Swords,
  dumbbell: Dumbbell,
  bike: Bike,
  activity: Activity,
  footprints: Footprints,
  mountain: Mountain,
  waves: Waves,
  sailboat: Sailboat,
  personStanding: PersonStanding,
  trendingUp: TrendingUp,
  zap: Zap,
  flame: Flame,

  // Activities - Food (18 icons)
  coffee: Coffee,
  cupSoda: CupSoda,
  pizza: Pizza,
  cake: Cake,
  iceCream: IceCream,
  apple: Apple,
  banana: Banana,
  cherry: Cherry,
  egg: Egg,
  fish: Fish,
  salad: Salad,
  utensils: Utensils,
  utensilsCrossed: UtensilsCrossed,
  wine: Wine,
  beer: Beer,
  martini: Martini,
  milk: Milk,
  cakeSlice: CakeSlice,

  // Activities - Travel (18 icons)
  plane: Plane,
  car: Car,
  bus: Bus,
  train: Train,
  ship: Ship,
  rocket: Rocket,
  luggage: Luggage,
  map: Map,
  mapPin: MapPin,
  mapPinned: MapPinned,
  compass: Compass,
  palmtree: Palmtree,
  tent: Tent,
  hotel: Hotel,
  home: Home,
  building: Building,
  store: Store,
  signpost: Signpost,

  // Activities - Arts & Reading (15 icons)
  book: Book,
  bookOpen: BookOpen,
  bookMarked: BookMarked,
  bookCopy: BookCopy,
  library: Library,
  graduationCap: GraduationCap,
  palette: Palette,
  paintbrush: Paintbrush,
  brush: Brush,
  pen: Pen,
  penTool: PenTool,
  pencil: Pencil,
  feather: Feather,
  layers: Layers,
  sparkles: Sparkles,

  // Games & Gaming (18 icons)
  gamepad: Gamepad,
  gamepad2: Gamepad2,
  joystick: Joystick,
  puzzle: Puzzle,
  dices: Dices,
  dice1: Dice1,
  dice2: Dice2,
  dice3: Dice3,
  dice4: Dice4,
  dice5: Dice5,
  dice6: Dice6,
  spade: Spade,
  club: Club,
  diamond: Diamond,
  shield: Shield,
  shieldCheck: ShieldCheck,
  axe: Axe,
  wand2: Wand2,
  bomb: Bomb,
  skull: Skull,
  ghost: Ghost,

  // Favorites - Hearts (9 icons)
  heart: Heart,
  heartPulse: HeartPulse,
  heartCrack: HeartCrack,
  heartHandshake: HeartHandshake,
  heartOff: HeartOff,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  handHeart: HandHeart,
  laugh: Laugh,

  // Favorites - Stars (7 icons)
  star: Star,
  starHalf: StarHalf,
  starOff: StarOff,
  sparkle: Sparkle,
  crown: Crown,
  gem: Gem,
  award: Award,

  // Favorites - Bookmarks (8 icons)
  bookmark: Bookmark,
  bookmarkPlus: BookmarkPlus,
  bookmarkMinus: BookmarkMinus,
  bookmarkCheck: BookmarkCheck,
  pin: Pin,
  pinOff: PinOff,
  paperclip: Paperclip,
  link: Link,

  // Favorites - Emotions (9 icons)
  smile: Smile,
  smilePlus: SmilePlus,
  meh: Meh,
  frown: Frown,
  angry: Angry,
  users: Users,
  user: User,
  userCheck: UserCheck,
  userPlus: UserPlus,

  // Organization - Folders (25 icons)
  folder: Folder,
  folderOpen: FolderOpen,
  folderClosed: FolderClosed,
  folderPlus: FolderPlus,
  folderMinus: FolderMinus,
  folderArchive: FolderArchive,
  folderCheck: FolderCheck,
  folderCog: FolderCog,
  folderHeart: FolderHeart,
  folderSync: FolderSync,
  file: File,
  fileText: FileText,
  fileCheck: FileCheck,
  filePlus: FilePlus,
  fileMinus: FileMinus,
  fileArchive: FileArchive,
  fileAudio: FileAudio,
  fileVideo: FileVideo,
  fileImage: FileImage,
  files: Files,
  inbox: Inbox,
  archive: Archive,
  package: Package,
  package2: Package2,
  packageCheck: PackageCheck,

  // Organization - Productivity (19 icons)
  boxes: Boxes,
  box: Box,
  container: Container,
  clipboard: Clipboard,
  clipboardCheck: ClipboardCheck,
  clipboardList: ClipboardList,
  list: List,
  listChecks: ListChecks,
  listOrdered: ListOrdered,
  kanban: Kanban,
  layers3: Layers3,
  grid3x3: Grid3x3,
  layoutGrid: LayoutGrid,
  layoutList: LayoutList,
  table: Table,
  columns: Columns,
  rows: Rows,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,

  // Symbols - Flags (7 icons)
  flag: Flag,
  flagTriangleRight: FlagTriangleRight,
  flagTriangleLeft: FlagTriangleLeft,
  milestone: Milestone,
  tags: Tags,
  tag: Tag,
  hash: Hash,

  // Symbols - Achievements (8 icons)
  badge: Badge,
  badgeCheck: BadgeCheck,
  badgeAlert: BadgeAlert,
  badgeHelp: BadgeHelp,
  shieldAlert: ShieldAlert,
  crosshair: Crosshair,
  gift: Gift,
  partyPopper: PartyPopper,

  // Symbols - Energy (6 icons)
  sun: Sun,
  moon: Moon,
  lightbulb: Lightbulb,
  battery: Battery,
  batteryCharging: BatteryCharging,
  bolt: Bolt,

  // Symbols - Security (6 icons)
  key: Key,
  keyRound: KeyRound,
  lock: Lock,
  lockOpen: LockOpen,
  unlock: Unlock,
  fingerprint: Fingerprint,

  // ============================================
  // NEW ICONS (367 icons)
  // ============================================

  // Nature & Weather (45 icons)
  cloud: Cloud,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  cloudSun: CloudSun,
  cloudMoon: CloudMoon,
  cloudFog: CloudFog,
  cloudDrizzle: CloudDrizzle,
  cloudLightning: CloudLightning,
  snowflake: Snowflake,
  rainbow: Rainbow,
  sunrise: Sunrise,
  sunset: Sunset,
  thermometer: Thermometer,
  thermometerSun: ThermometerSun,
  thermometerSnowflake: ThermometerSnowflake,
  wind: Wind,
  tornado: Tornado,
  droplets: Droplets,
  droplet: Droplet,
  umbrella: Umbrella,
  treePine: TreePine,
  treeDeciduous: TreeDeciduous,
  trees: Trees,
  sprout: Sprout,
  leaf: Leaf,
  flower: Flower,
  flower2: Flower2,
  clover: Clover,
  shrub: Shrub,
  vegan: Vegan,
  treePalm: TreePalm,
  mountainSnow: MountainSnow,
  shell: Shell,
  cloudy: Cloudy,
  cloudOff: CloudOff,
  cloudCog: CloudCog,
  cloudDownload: CloudDownload,
  cloudUpload: CloudUpload,
  sunMoon: SunMoon,
  sunDim: SunDim,
  sunMedium: SunMedium,
  moonStar: MoonStar,
  haze: Haze,
  eclipse: Eclipse,
  stars: Stars,

  // Animals (18 icons)
  cat: Cat,
  dog: Dog,
  rabbit: Rabbit,
  rat: Rat,
  squirrel: Squirrel,
  bird: Bird,
  bug: Bug,
  turtle: Turtle,
  snail: Snail,
  worm: Worm,
  bugPlay: BugPlay,
  bugOff: BugOff,
  bone: Bone,
  beef: Beef,
  pawPrint: PawPrint,
  fishSymbol: FishSymbol,
  fishOff: FishOff,
  featherAnimal: FeatherAnimal,

  // Technology (50 icons)
  cpu: Cpu,
  hardDrive: HardDrive,
  database: Database,
  databaseBackup: DatabaseBackup,
  server: Server,
  serverCog: ServerCog,
  serverCrash: ServerCrash,
  terminal: Terminal,
  terminalSquare: TerminalSquare,
  code: Code,
  code2: Code2,
  fileCode: FileCode,
  fileCode2: FileCode2,
  braces: Braces,
  binary: Binary,
  wifi: Wifi,
  wifiOff: WifiOff,
  bluetooth: Bluetooth,
  bluetoothConnected: BluetoothConnected,
  bluetoothOff: BluetoothOff,
  bluetoothSearching: BluetoothSearching,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  laptop2: Laptop2,
  mouse: Mouse,
  mousePointer: MousePointer,
  mousePointer2: MousePointer2,
  keyboard: Keyboard,
  usb: Usb,
  hardDriveDownload: HardDriveDownload,
  hardDriveUpload: HardDriveUpload,
  plug: Plug,
  power: Power,
  powerOff: PowerOff,
  qrCode: QrCode,
  scanLine: ScanLine,
  scan: Scan,
  router: Router,
  cable: Cable,
  cast: Cast,
  signal: Signal,
  signalHigh: SignalHigh,
  signalLow: SignalLow,
  signalMedium: SignalMedium,
  signalZero: SignalZero,
  nfc: Nfc,
  monitorSmartphone: MonitorSmartphone,
  serverOff: ServerOff,
  databaseZap: DatabaseZap,

  // Shapes & Symbols (40 icons)
  circle: Circle,
  circleDot: CircleDot,
  square: Square,
  squareCheck: SquareCheck,
  squareDot: SquareDot,
  triangle: Triangle,
  pentagon: Pentagon,
  hexagon: Hexagon,
  octagon: Octagon,
  plus: Plus,
  plusCircle: PlusCircle,
  plusSquare: PlusSquare,
  minus: Minus,
  minusCircle: MinusCircle,
  minusSquare: MinusSquare,
  xCircle: XCircle,
  xSquare: XSquare,
  equal: Equal,
  equalNot: EqualNot,
  divide: Divide,
  percent: Percent,
  infinity: Infinity,
  circleSlash: CircleSlash,
  squareSlash: SquareSlash,
  atSign: AtSign,
  dollarSign: DollarSign,
  euro: Euro,
  poundSterling: PoundSterling,
  indianRupee: IndianRupee,
  japaneseYen: JapaneseYen,
  swissFranc: SwissFranc,
  russianRuble: RussianRuble,
  asterisk: Asterisk,
  circleDashed: CircleDashed,
  squareDashedBottom: SquareDashedBottom,
  triangleAlert: TriangleAlert,
  octagonAlert: OctagonAlert,
  circleAlert: CircleAlert,
  circleCheck: CircleCheck,
  squareX: SquareX,

  // Communication (35 icons)
  mail: Mail,
  mailOpen: MailOpen,
  mailCheck: MailCheck,
  mailX: MailX,
  mailPlus: MailPlus,
  mailMinus: MailMinus,
  mailWarning: MailWarning,
  mailQuestion: MailQuestion,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  messageCircleQuestion: MessageCircleQuestion,
  messagesSquare: MessagesSquare,
  send: Send,
  sendHorizontal: SendHorizontal,
  phone: Phone,
  phoneCall: PhoneCall,
  phoneForwarded: PhoneForwarded,
  phoneIncoming: PhoneIncoming,
  phoneMissed: PhoneMissed,
  phoneOff: PhoneOff,
  phoneOutgoing: PhoneOutgoing,
  voicemail: Voicemail,
  contact: Contact,
  contact2: Contact2,
  megaphone: Megaphone,
  bell: Bell,
  bellOff: BellOff,
  bellRing: BellRing,
  bellDot: BellDot,
  bellMinus: BellMinus,
  bellPlus: BellPlus,
  rss: Rss,
  atSignComm: AtSignComm,
  reply: Reply,
  forward: Forward,

  // Time & Calendar (30 icons)
  clock: Clock,
  clock1: Clock1,
  clock2: Clock2,
  clock3: Clock3,
  clock4: Clock4,
  clock5: Clock5,
  clock6: Clock6,
  clock7: Clock7,
  clock8: Clock8,
  clock9: Clock9,
  clock10: Clock10,
  clock11: Clock11,
  clock12: Clock12,
  timer: Timer,
  timerOff: TimerOff,
  timerReset: TimerReset,
  hourglass: Hourglass,
  alarmClock: AlarmClock,
  alarmClockOff: AlarmClockOff,
  calendar: Calendar,
  calendarDays: CalendarDays,
  calendarCheck: CalendarCheck,
  calendarClock: CalendarClock,
  calendarX: CalendarX,
  calendarPlus: CalendarPlus,
  calendarMinus: CalendarMinus,
  calendarRange: CalendarRange,
  calendarHeart: CalendarHeart,
  history: History,
  watch: Watch,

  // Business & Finance (35 icons)
  briefcase: Briefcase,
  creditCard: CreditCard,
  receipt: Receipt,
  banknote: Banknote,
  coins: Coins,
  wallet: Wallet,
  piggyBank: PiggyBank,
  trendingDown: TrendingDown,
  barChart: BarChart,
  barChart2: BarChart2,
  barChart3: BarChart3,
  barChart4: BarChart4,
  lineChart: LineChart,
  pieChart: PieChart,
  scale: Scale,
  calculator: Calculator,
  landmark: Landmark,
  building2: Building2,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  shoppingBasket: ShoppingBasket,
  truck: Truck,
  circleDollarSign: CircleDollarSign,
  badgeDollarSign: BadgeDollarSign,
  badgePercent: BadgePercent,
  receiptText: ReceiptText,
  handCoins: HandCoins,
  arrowUpDown: ArrowUpDown,
  arrowDownUp: ArrowDownUp,
  presentation: Presentation,
  briefcaseBusiness: BriefcaseBusiness,
  factory: Factory,
  warehouse: Warehouse,
  receiptEuro: ReceiptEuro,
  receiptPoundSterling: ReceiptPoundSterling,

  // Health & Medical (20 icons)
  pill: Pill,
  stethoscope: Stethoscope,
  syringe: Syringe,
  ambulance: Ambulance,
  cross: Cross,
  hospital: Hospital,
  dna: Dna,
  microscope: Microscope,
  testTube: TestTube,
  testTubes: TestTubes,
  flaskConical: FlaskConical,
  flaskRound: FlaskRound,
  accessibility: Accessibility,
  brain: Brain,
  ear: Ear,
  eye: Eye,
  eyeOff: EyeOff,
  hand: Hand,
  medicalScan: MedicalScan,
  medicalHeart: MedicalHeart,

  // Tools & Construction (34 icons)
  wrench: Wrench,
  hammer: Hammer,
  drill: Drill,
  pickaxe: Pickaxe,
  shovel: Shovel,
  scissors: Scissors,
  ruler: Ruler,
  circuitBoard: CircuitBoard,
  component: Component,
  settings: Settings,
  settings2: Settings2,
  cog: Cog,
  sliders: Sliders,
  slidersHorizontal: SlidersHorizontal,
  slidersVertical: SlidersVertical,
  construction: Construction,
  gauge: Gauge,
  magnet: Magnet,
  unlink: Unlink,
  search: Search,
  searchCheck: SearchCheck,
  searchX: SearchX,
  searchCode: SearchCode,
  searchSlash: SearchSlash,
  telescope: Telescope,
  scaling: Scaling,
  pipette: Pipette,
  paintbrush2: Paintbrush2,
  paintBucket: PaintBucket,
  eraser: Eraser,
  highlighter: Highlighter,
  shapes: Shapes,
  slice: Slice,
  zoomIn: ZoomIn,

  // Arrows & Navigation (35 icons)
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  arrowUpLeft: ArrowUpLeft,
  arrowDownRight: ArrowDownRight,
  arrowDownLeft: ArrowDownLeft,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUp: ChevronsUp,
  chevronsDown: ChevronsDown,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronsUpDown: ChevronsUpDown,
  chevronsLeftRight: ChevronsLeftRight,
  moveUp: MoveUp,
  moveDown: MoveDown,
  moveLeft: MoveLeft,
  moveRight: MoveRight,
  moveHorizontal: MoveHorizontal,
  moveVertical: MoveVertical,
  move: Move,
  moveDiagonal: MoveDiagonal,
  moveDiagonal2: MoveDiagonal2,
  maximize: Maximize,
  minimize: Minimize,
  maximize2: Maximize2,
  minimize2: Minimize2,
  expand: Expand,
  shrink: Shrink,
  navigation: Navigation,
  navigation2: Navigation2,

  // Miscellaneous (22 icons)
  glasses: Glasses,
  lamp: Lamp,
  lampDesk: LampDesk,
  lampFloor: LampFloor,
  lampCeiling: LampCeiling,
  lampWallDown: LampWallDown,
  lampWallUp: LampWallUp,
  flashlight: Flashlight,
  flashlightOff: FlashlightOff,
  cigarette: Cigarette,
  baby: Baby,
  shirt: Shirt,
  sofa: Sofa,
  bed: Bed,
  bedDouble: BedDouble,
  bedSingle: BedSingle,
  bath: Bath,
  armchair: Armchair,
  doorOpen: DoorOpen,
  doorClosed: DoorClosed,
  blinds: Blinds,
  fan: Fan,
} as const;

/**
 * Type-safe icon name (literal union of all icon keys)
 * Use this type for icon fields in interfaces
 * Automatically updated when PLAYLIST_ICONS changes
 */
export type PlaylistIconName = keyof typeof PLAYLIST_ICONS;

/**
 * Icon categories for organized browsing in IconSelector
 * Organized into 600 icons across 12 main categories
 */
export const ICON_CATEGORIES = {
  media: {
    label: 'Media',
    icons: [
      // Audio (15)
      'music',
      'music2',
      'mic',
      'radio',
      'headphones',
      'volume2',
      'volume',
      'volumeX',
      'speaker',
      'podcast',
      'disc',
      'disc2',
      'disc3',
      'audioLines',
      'audioWaveform',
      // Video (18)
      'film',
      'video',
      'videoOff',
      'camera',
      'cameraOff',
      'clapperboard',
      'tv',
      'tv2',
      'monitor',
      'monitorPlay',
      'projector',
      'webcam',
      'play',
      'playCircle',
      'pause',
      'pauseCircle',
      'skipForward',
      'skipBack',
      // Images (12)
      'image',
      'imageOff',
      'imagePlus',
      'images',
      'galleryHorizontal',
      'galleryVertical',
      'galleryVerticalEnd',
      'crop',
      'filter',
      'aperture',
      'focus',
      'scanFace',
    ] as const,
  },
  activities: {
    label: 'Activities',
    icons: [
      // Sports (15)
      'trophy',
      'medal',
      'target',
      'swords',
      'dumbbell',
      'bike',
      'activity',
      'footprints',
      'mountain',
      'waves',
      'sailboat',
      'personStanding',
      'trendingUp',
      'zap',
      'flame',
      // Food (18)
      'coffee',
      'cupSoda',
      'pizza',
      'cake',
      'iceCream',
      'apple',
      'banana',
      'cherry',
      'egg',
      'fish',
      'salad',
      'utensils',
      'utensilsCrossed',
      'wine',
      'beer',
      'martini',
      'milk',
      'cakeSlice',
      // Travel (18)
      'plane',
      'car',
      'bus',
      'train',
      'ship',
      'rocket',
      'luggage',
      'map',
      'mapPin',
      'mapPinned',
      'compass',
      'palmtree',
      'tent',
      'hotel',
      'home',
      'building',
      'store',
      'signpost',
      // Arts & Reading (15)
      'book',
      'bookOpen',
      'bookMarked',
      'bookCopy',
      'library',
      'graduationCap',
      'palette',
      'paintbrush',
      'brush',
      'pen',
      'penTool',
      'pencil',
      'feather',
      'layers',
      'sparkles',
    ] as const,
  },
  games: {
    label: 'Games',
    icons: [
      'gamepad',
      'gamepad2',
      'joystick',
      'puzzle',
      'dices',
      'dice1',
      'dice2',
      'dice3',
      'dice4',
      'dice5',
      'dice6',
      'spade',
      'club',
      'diamond',
      'shield',
      'shieldCheck',
      'axe',
      'wand2',
      'bomb',
      'skull',
      'ghost',
    ] as const,
  },
  favorites: {
    label: 'Favorites',
    icons: [
      // Hearts (9)
      'heart',
      'heartPulse',
      'heartCrack',
      'heartHandshake',
      'heartOff',
      'thumbsUp',
      'thumbsDown',
      'handHeart',
      'laugh',
      // Stars (7)
      'star',
      'starHalf',
      'starOff',
      'sparkle',
      'crown',
      'gem',
      'award',
      // Bookmarks (8)
      'bookmark',
      'bookmarkPlus',
      'bookmarkMinus',
      'bookmarkCheck',
      'pin',
      'pinOff',
      'paperclip',
      'link',
      // Emotions (9)
      'smile',
      'smilePlus',
      'meh',
      'frown',
      'angry',
      'users',
      'user',
      'userCheck',
      'userPlus',
    ] as const,
  },
  organization: {
    label: 'Organization',
    icons: [
      // Folders & Files (25)
      'folder',
      'folderOpen',
      'folderClosed',
      'folderPlus',
      'folderMinus',
      'folderArchive',
      'folderCheck',
      'folderCog',
      'folderHeart',
      'folderSync',
      'file',
      'fileText',
      'fileCheck',
      'filePlus',
      'fileMinus',
      'fileArchive',
      'fileAudio',
      'fileVideo',
      'fileImage',
      'files',
      'inbox',
      'archive',
      'package',
      'package2',
      'packageCheck',
      // Productivity (19)
      'boxes',
      'box',
      'container',
      'clipboard',
      'clipboardCheck',
      'clipboardList',
      'list',
      'listChecks',
      'listOrdered',
      'kanban',
      'layers3',
      'grid3x3',
      'layoutGrid',
      'layoutList',
      'table',
      'columns',
      'rows',
      'alignLeft',
      'alignCenter',
    ] as const,
  },
  symbols: {
    label: 'Symbols',
    icons: [
      // Flags (7)
      'flag',
      'flagTriangleRight',
      'flagTriangleLeft',
      'milestone',
      'tags',
      'tag',
      'hash',
      // Achievements (8)
      'badge',
      'badgeCheck',
      'badgeAlert',
      'badgeHelp',
      'shieldAlert',
      'crosshair',
      'gift',
      'partyPopper',
      // Energy (6)
      'sun',
      'moon',
      'lightbulb',
      'battery',
      'batteryCharging',
      'bolt',
      // Security (6)
      'key',
      'keyRound',
      'lock',
      'lockOpen',
      'unlock',
      'fingerprint',
    ] as const,
  },

  // ============================================
  // NEW CATEGORIES
  // ============================================

  nature: {
    label: 'Nature & Weather',
    icons: [
      // Weather (30)
      'cloud',
      'cloudRain',
      'cloudSnow',
      'cloudSun',
      'cloudMoon',
      'cloudFog',
      'cloudDrizzle',
      'cloudLightning',
      'snowflake',
      'rainbow',
      'sunrise',
      'sunset',
      'thermometer',
      'thermometerSun',
      'thermometerSnowflake',
      'wind',
      'tornado',
      'droplets',
      'droplet',
      'umbrella',
      'cloudy',
      'cloudOff',
      'cloudCog',
      'cloudDownload',
      'cloudUpload',
      'sunMoon',
      'sunDim',
      'sunMedium',
      'moonStar',
      'haze',
      'eclipse',
      'stars',
      // Plants & Trees (13)
      'treePine',
      'treeDeciduous',
      'trees',
      'sprout',
      'leaf',
      'flower',
      'flower2',
      'clover',
      'shrub',
      'vegan',
      'treePalm',
      'mountainSnow',
      'shell',
    ] as const,
  },
  animals: {
    label: 'Animals',
    icons: [
      'cat',
      'dog',
      'rabbit',
      'rat',
      'squirrel',
      'bird',
      'bug',
      'turtle',
      'snail',
      'worm',
      'bugPlay',
      'bugOff',
      'bone',
      'beef',
      'pawPrint',
      'fishSymbol',
      'fishOff',
      'featherAnimal',
    ] as const,
  },
  technology: {
    label: 'Technology',
    icons: [
      // Hardware (25)
      'cpu',
      'hardDrive',
      'database',
      'databaseBackup',
      'server',
      'serverCog',
      'serverCrash',
      'serverOff',
      'databaseZap',
      'smartphone',
      'tablet',
      'laptop',
      'laptop2',
      'mouse',
      'mousePointer',
      'mousePointer2',
      'keyboard',
      'usb',
      'hardDriveDownload',
      'hardDriveUpload',
      'plug',
      'power',
      'powerOff',
      'monitorSmartphone',
      'router',
      // Development (10)
      'terminal',
      'terminalSquare',
      'code',
      'code2',
      'fileCode',
      'fileCode2',
      'braces',
      'binary',
      'circuitBoard',
      'component',
      // Connectivity (15)
      'wifi',
      'wifiOff',
      'bluetooth',
      'bluetoothConnected',
      'bluetoothOff',
      'bluetoothSearching',
      'qrCode',
      'scanLine',
      'scan',
      'cable',
      'cast',
      'signal',
      'signalHigh',
      'signalLow',
      'signalMedium',
      'signalZero',
      'nfc',
    ] as const,
  },
  shapes: {
    label: 'Shapes & Symbols',
    icons: [
      // Geometric (10)
      'circle',
      'circleDot',
      'square',
      'squareCheck',
      'squareDot',
      'triangle',
      'pentagon',
      'hexagon',
      'octagon',
      'shapes',
      // Math & Operators (12)
      'plus',
      'plusCircle',
      'plusSquare',
      'minus',
      'minusCircle',
      'minusSquare',
      'xCircle',
      'xSquare',
      'equal',
      'equalNot',
      'divide',
      'percent',
      'infinity',
      // Styled Shapes (8)
      'circleSlash',
      'squareSlash',
      'circleDashed',
      'squareDashedBottom',
      'circleAlert',
      'circleCheck',
      'squareX',
      'asterisk',
      // Currency (8)
      'atSign',
      'dollarSign',
      'euro',
      'poundSterling',
      'indianRupee',
      'japaneseYen',
      'swissFranc',
      'russianRuble',
      // Alerts (3)
      'triangleAlert',
      'octagonAlert',
    ] as const,
  },
  communication: {
    label: 'Communication',
    icons: [
      // Mail (8)
      'mail',
      'mailOpen',
      'mailCheck',
      'mailX',
      'mailPlus',
      'mailMinus',
      'mailWarning',
      'mailQuestion',
      // Messages (5)
      'messageCircle',
      'messageSquare',
      'messageCircleQuestion',
      'messagesSquare',
      'rss',
      // Send (4)
      'send',
      'sendHorizontal',
      'reply',
      'forward',
      // Phone (8)
      'phone',
      'phoneCall',
      'phoneForwarded',
      'phoneIncoming',
      'phoneMissed',
      'phoneOff',
      'phoneOutgoing',
      'voicemail',
      // Contacts & Alerts (10)
      'contact',
      'contact2',
      'megaphone',
      'bell',
      'bellOff',
      'bellRing',
      'bellDot',
      'bellMinus',
      'bellPlus',
      'atSignComm',
    ] as const,
  },
  time: {
    label: 'Time & Calendar',
    icons: [
      // Clocks (13)
      'clock',
      'clock1',
      'clock2',
      'clock3',
      'clock4',
      'clock5',
      'clock6',
      'clock7',
      'clock8',
      'clock9',
      'clock10',
      'clock11',
      'clock12',
      // Timers (5)
      'timer',
      'timerOff',
      'timerReset',
      'hourglass',
      'watch',
      // Alarms (2)
      'alarmClock',
      'alarmClockOff',
      // Calendar (9)
      'calendar',
      'calendarDays',
      'calendarCheck',
      'calendarClock',
      'calendarX',
      'calendarPlus',
      'calendarMinus',
      'calendarRange',
      'calendarHeart',
      // History (1)
      'history',
    ] as const,
  },
  business: {
    label: 'Business & Finance',
    icons: [
      // Money (10)
      'briefcase',
      'creditCard',
      'receipt',
      'banknote',
      'coins',
      'wallet',
      'piggyBank',
      'circleDollarSign',
      'badgeDollarSign',
      'handCoins',
      // Charts (7)
      'trendingDown',
      'barChart',
      'barChart2',
      'barChart3',
      'barChart4',
      'lineChart',
      'pieChart',
      // Business (10)
      'scale',
      'calculator',
      'landmark',
      'building2',
      'presentation',
      'briefcaseBusiness',
      'factory',
      'warehouse',
      'badgePercent',
      'arrowUpDown',
      // Shopping (4)
      'shoppingBag',
      'shoppingCart',
      'shoppingBasket',
      'truck',
      // Receipts (4)
      'receiptText',
      'arrowDownUp',
      'receiptEuro',
      'receiptPoundSterling',
    ] as const,
  },
  health: {
    label: 'Health & Medical',
    icons: [
      // Medical Equipment (6)
      'pill',
      'stethoscope',
      'syringe',
      'ambulance',
      'cross',
      'hospital',
      // Science (6)
      'dna',
      'microscope',
      'testTube',
      'testTubes',
      'flaskConical',
      'flaskRound',
      // Body (8)
      'accessibility',
      'brain',
      'ear',
      'eye',
      'eyeOff',
      'hand',
      'medicalScan',
      'medicalHeart',
    ] as const,
  },
  tools: {
    label: 'Tools & Construction',
    icons: [
      // Hand Tools (7)
      'wrench',
      'hammer',
      'drill',
      'pickaxe',
      'shovel',
      'scissors',
      'ruler',
      // Settings (7)
      'settings',
      'settings2',
      'cog',
      'sliders',
      'slidersHorizontal',
      'slidersVertical',
      'gauge',
      // Construction (3)
      'construction',
      'magnet',
      'unlink',
      // Search (5)
      'search',
      'searchCheck',
      'searchX',
      'searchCode',
      'searchSlash',
      // Optical (3)
      'telescope',
      'scaling',
      'zoomIn',
      // Art Tools (9)
      'pipette',
      'paintbrush2',
      'paintBucket',
      'eraser',
      'highlighter',
      'shapes',
      'slice',
      'circuitBoard',
      'component',
    ] as const,
  },
  arrows: {
    label: 'Arrows & Navigation',
    icons: [
      // Basic Arrows (8)
      'arrowUp',
      'arrowDown',
      'arrowLeft',
      'arrowRight',
      'arrowUpRight',
      'arrowUpLeft',
      'arrowDownRight',
      'arrowDownLeft',
      // Chevrons (10)
      'chevronUp',
      'chevronDown',
      'chevronLeft',
      'chevronRight',
      'chevronsUp',
      'chevronsDown',
      'chevronsLeft',
      'chevronsRight',
      'chevronsUpDown',
      'chevronsLeftRight',
      // Move (9)
      'moveUp',
      'moveDown',
      'moveLeft',
      'moveRight',
      'moveHorizontal',
      'moveVertical',
      'move',
      'moveDiagonal',
      'moveDiagonal2',
      // Size (6)
      'maximize',
      'minimize',
      'maximize2',
      'minimize2',
      'expand',
      'shrink',
      // Navigation (2)
      'navigation',
      'navigation2',
    ] as const,
  },
  home: {
    label: 'Home & Miscellaneous',
    icons: [
      // Vision (2)
      'glasses',
      // Lighting (8)
      'lamp',
      'lampDesk',
      'lampFloor',
      'lampCeiling',
      'lampWallDown',
      'lampWallUp',
      'flashlight',
      'flashlightOff',
      // People (2)
      'cigarette',
      'baby',
      // Clothing (1)
      'shirt',
      // Furniture (7)
      'sofa',
      'bed',
      'bedDouble',
      'bedSingle',
      'bath',
      'armchair',
      // Doors & Windows (3)
      'doorOpen',
      'doorClosed',
      'blinds',
      // Appliances (1)
      'fan',
    ] as const,
  },
} as const satisfies Record<string, { label: string; icons: readonly PlaylistIconName[] }>;

/**
 * Get icon component by name with fallback
 * Returns ListVideo icon if iconName is null, undefined, or invalid
 *
 * @param iconName - Icon name from the PLAYLIST_ICONS registry
 * @returns LucideIcon component
 *
 * @example
 * const Icon = getPlaylistIcon('music');
 * const FallbackIcon = getPlaylistIcon(null); // Returns ListVideo
 */
export function getPlaylistIcon(iconName: PlaylistIconName | null | undefined): LucideIcon {
  if (!iconName || !(iconName in PLAYLIST_ICONS)) {
    return ListVideo; // Default fallback
  }
  return PLAYLIST_ICONS[iconName];
}

/**
 * Get all icon names as array (for iteration)
 *
 * @returns Array of all valid playlist icon names
 *
 * @example
 * const allIcons = getAllIconNames();
 * allIcons.forEach(iconName => {
 *   const Icon = getPlaylistIcon(iconName);
 *   // render icon
 * });
 */
export function getAllIconNames(): PlaylistIconName[] {
  return Object.keys(PLAYLIST_ICONS) as PlaylistIconName[];
}
